### ISSUE TITLE
Remove last ',' from json file.

### ISSUE THREAD

**Issue by kiranshahi** [kiranshahi/CSV-to-JSON-CLI#1]
I am trying to generate File from CSV file. [here is the CSV](https://github.com/kiranshahi/CSV-to-JSON-CLI/blob/master/test.csv) and [Here is the generated CSV](https://github.com/kiranshahi/CSV-to-JSON-CLI/blob/master/new.json) currently last object on JSON file have , on it. It must not be included

**Comment by SamuelsSantos** [comment]
I can try to fix this!
